Cpu physical cores
JuliaParallel/Hwloc.jl pull request #13
Opened 2017-08-16 19:25 UTC by juliohm

Fix #10.

This is a simple utility for the most commonly used query. I appreciate if you can review it.

I thought of saving the result in a constant CPU_PHYSICAL_CORES but I am not sure it is safe to assume the number will be the same across a cluster of computers for example.

2017-08-16 20:59 UTC, eschnett requested changes
I would rename the function to `num_physical_cores`. I find the prefix `cpu` a bit confusing. (Is it the number of cores of one CPU only? No, it's the number of cores in a whole node.)

2017-08-16 21:10 UTC, juliohm commented
Makes total sense @eschnett , thanks. I have pushed the changes and added an extra test for it.

2017-08-17 02:17 UTC, eschnett approved these changes

2017-08-17 02:30 UTC, merged

2017-11-14 03:07 UTC, GregPlowman commented
Is it possible to tag a new release to incorporate this utility function?

2017-11-14 03:28 UTC, juliohm commented
@eschnett I thought we had tagged a new version after this PR was merged, could you please take care of it?

2017-11-14 14:01 UTC, eschnett commented
@juliohm I don't recall. I believe you have write access to the repository -- can you tag a new version yourself?

2017-11-14 16:09 UTC, juliohm commented
Thank you @eschnett, I tagged a new version.